### ISSUE TITLE
Chapter 6 - ERR_DIRECT_INVOKE - "app channel is not initialized" 

### ISSUE THREAD

**Issue by bcraun** [Apress/introducing-dapr#2]
I'm attempting to run the gRPC Server sample from Chapter 6 on an nVIDIA Jetson Nano (ARM Linux X64) using .NET 6 with DAPR 1.5.1 and am getting the following error from the curl command:

`$ curl -X POST http://localhost:3500/v1.0/invoke/greetinggrpc/method/SayHello -d "{'name':'world'}"`

`{"errorCode":"ERR_DIRECT_INVOKE","message":"fail to invoke, id: greetinggrpc, err: rpc error: code = Internal desc = app channel is not initialized"}`

App is started using the following with no errors:

`$ dapr run --app-id greetinggrpc --app-port 5000 --app-protocol grpc -- dotnet run`

> ℹ️  Starting Dapr with id greetinggrpc. HTTP Port: 41763. gRPC Port: 39059
> INFO[0000] starting Dapr Runtime -- version 1.5.1 -- commit c6daae8e9b11b3e241a9cb84c33e5aa740d74368  app_id=greetinggrpc instance=jetson-nano scope=dapr.runtime type=log ver=1.5.1
> INFO[0000] log level set to: info                        app_id=greetinggrpc instance=jetson-nano scope=dapr.runtime type=log ver=1.5.1
> INFO[0000] metrics server started on :39581/             app_id=greetinggrpc instance=jetson-nano scope=dapr.metrics type=log ver=1.5.1
> INFO[0000] standalone mode configured                    app_id=greetinggrpc instance=jetson-nano scope=dapr.runtime type=log ver=1.5.1
> INFO[0000] app id: greetinggrpc                          app_id=greetinggrpc instance=jetson-nano scope=dapr.runtime type=log ver=1.5.1
> INFO[0000] mTLS is disabled. Skipping certificate request and tls validation  app_id=greetinggrpc instance=jetson-nano scope=dapr.runtime type=log ver=1.5.1
> INFO[0000] local service entry announced: greetinggrpc -> 192.168.50.150:33573  app_id=greetinggrpc instance=jetson-nano scope=dapr.contrib type=log ver=1.5.1
> INFO[0000] Initialized name resolution to mdns           app_id=greetinggrpc instance=jetson-nano scope=dapr.runtime type=log ver=1.5.1
> INFO[0000] loading components                            app_id=greetinggrpc instance=jetson-nano scope=dapr.runtime type=log ver=1.5.1
> INFO[0000] component loaded. name: pubsub, type: pubsub.redis/v1  app_id=greetinggrpc instance=jetson-nano scope=dapr.runtime type=log ver=1.5.1
> INFO[0000] waiting for all outstanding components to be processed  app_id=greetinggrpc instance=jetson-nano scope=dapr.runtime type=log ver=1.5.1
> INFO[0000] component loaded. name: statestore, type: state.redis/v1  app_id=greetinggrpc instance=jetson-nano scope=dapr.runtime type=log ver=1.5.1
> INFO[0000] all outstanding components processed          app_id=greetinggrpc instance=jetson-nano scope=dapr.runtime type=log ver=1.5.1
> INFO[0000] enabled gRPC tracing middleware               app_id=greetinggrpc instance=jetson-nano scope=dapr.runtime.grpc.api type=log ver=1.5.1
> INFO[0000] enabled gRPC metrics middleware               app_id=greetinggrpc instance=jetson-nano scope=dapr.runtime.grpc.api type=log ver=1.5.1
> INFO[0000] API gRPC server is running on port 39059      app_id=greetinggrpc instance=jetson-nano scope=dapr.runtime type=log ver=1.5.1
> INFO[0000] enabled metrics http middleware               app_id=greetinggrpc instance=jetson-nano scope=dapr.runtime.http type=log ver=1.5.1
> INFO[0000] enabled tracing http middleware               app_id=greetinggrpc instance=jetson-nano scope=dapr.runtime.http type=log ver=1.5.1
> INFO[0000] http server is running on port 41763          app_id=greetinggrpc instance=jetson-nano scope=dapr.runtime type=log ver=1.5.1
> INFO[0000] The request body size parameter is: 4         app_id=greetinggrpc instance=jetson-nano scope=dapr.runtime type=log ver=1.5.1
> INFO[0000] enabled gRPC tracing middleware               app_id=greetinggrpc instance=jetson-nano scope=dapr.runtime.grpc.internal type=log ver=1.5.1
> INFO[0000] enabled gRPC metrics middleware               app_id=greetinggrpc instance=jetson-nano scope=dapr.runtime.grpc.internal type=log ver=1.5.1
> INFO[0000] internal gRPC server is running on port 33573  app_id=greetinggrpc instance=jetson-nano scope=dapr.runtime type=log ver=1.5.1
> INFO[0000] application protocol: grpc. waiting on port 5000.  This will block until the app is listening on that port.  app_id=greetinggrpc instance=jetson-nano scope=dapr.runtime type=log ver=1.5.1
> == APP == Building...
> ℹ️  Updating metadata for app command: dotnet run
> ✅  You're up and running! Both Dapr and your app logs will appear here.
> 
> == APP == info: Microsoft.Hosting.Lifetime[14]
> == APP ==       Now listening on: http://localhost:5070
> == APP == info: Microsoft.Hosting.Lifetime[14]
> == APP ==       Now listening on: https://localhost:7071
> == APP == info: Microsoft.Hosting.Lifetime[0]
> == APP ==       Application started. Press Ctrl+C to shut down.
> == APP == info: Microsoft.Hosting.Lifetime[0]
> == APP ==       Hosting environment: Development
> == APP == info: Microsoft.Hosting.Lifetime[0]
> == APP ==       Content root path: /home/jetson/projects/dapr-grpc/GreetingGRPC

Test sidecar is started using the following with no errors:

`$ dapr run --app-id myapp --dapr-http-port 3500 --`

> 
> WARNING: no application command found.
> ℹ️  Starting Dapr with id Napeequinox-Sword. HTTP Port: 3500. gRPC Port: 34427
> ℹ️  Checking if Dapr sidecar is listening on HTTP port 3500
> INFO[0000] starting Dapr Runtime -- version 1.5.1 -- commit c6daae8e9b11b3e241a9cb84c33e5aa740d74368  app_id=Napeequinox-Sword instance=jetson-nano scope=dapr.runtime type=log ver=1.5.1
> INFO[0000] log level set to: info                        app_id=Napeequinox-Sword instance=jetson-nano scope=dapr.runtime type=log ver=1.5.1
> INFO[0000] metrics server started on :39407/             app_id=Napeequinox-Sword instance=jetson-nano scope=dapr.metrics type=log ver=1.5.1
> INFO[0000] standalone mode configured                    app_id=Napeequinox-Sword instance=jetson-nano scope=dapr.runtime type=log ver=1.5.1
> INFO[0000] app id: Napeequinox-Sword                     app_id=Napeequinox-Sword instance=jetson-nano scope=dapr.runtime type=log ver=1.5.1
> INFO[0000] mTLS is disabled. Skipping certificate request and tls validation  app_id=Napeequinox-Sword instance=jetson-nano scope=dapr.runtime type=log ver=1.5.1
> INFO[0000] local service entry announced: Napeequinox-Sword -> 192.168.50.150:45707  app_id=Napeequinox-Sword instance=jetson-nano scope=dapr.contrib type=log ver=1.5.1
> INFO[0000] Initialized name resolution to mdns           app_id=Napeequinox-Sword instance=jetson-nano scope=dapr.runtime type=log ver=1.5.1
> INFO[0000] loading components                            app_id=Napeequinox-Sword instance=jetson-nano scope=dapr.runtime type=log ver=1.5.1
> INFO[0000] component loaded. name: pubsub, type: pubsub.redis/v1  app_id=Napeequinox-Sword instance=jetson-nano scope=dapr.runtime type=log ver=1.5.1
> INFO[0000] waiting for all outstanding components to be processed  app_id=Napeequinox-Sword instance=jetson-nano scope=dapr.runtime type=log ver=1.5.1
> INFO[0000] component loaded. name: statestore, type: state.redis/v1  app_id=Napeequinox-Sword instance=jetson-nano scope=dapr.runtime type=log ver=1.5.1
> INFO[0000] all outstanding components processed          app_id=Napeequinox-Sword instance=jetson-nano scope=dapr.runtime type=log ver=1.5.1
> INFO[0000] enabled gRPC tracing middleware               app_id=Napeequinox-Sword instance=jetson-nano scope=dapr.runtime.grpc.api type=log ver=1.5.1
> INFO[0000] enabled gRPC metrics middleware               app_id=Napeequinox-Sword instance=jetson-nano scope=dapr.runtime.grpc.api type=log ver=1.5.1
> INFO[0000] API gRPC server is running on port 34427      app_id=Napeequinox-Sword instance=jetson-nano scope=dapr.runtime type=log ver=1.5.1
> INFO[0000] enabled metrics http middleware               app_id=Napeequinox-Sword instance=jetson-nano scope=dapr.runtime.http type=log ver=1.5.1
> INFO[0000] enabled tracing http middleware               app_id=Napeequinox-Sword instance=jetson-nano scope=dapr.runtime.http type=log ver=1.5.1
> INFO[0000] http server is running on port 3500           app_id=Napeequinox-Sword instance=jetson-nano scope=dapr.runtime type=log ver=1.5.1
> INFO[0000] The request body size parameter is: 4         app_id=Napeequinox-Sword instance=jetson-nano scope=dapr.runtime type=log ver=1.5.1
> INFO[0000] enabled gRPC tracing middleware               app_id=Napeequinox-Sword instance=jetson-nano scope=dapr.runtime.grpc.internal type=log ver=1.5.1
> INFO[0000] enabled gRPC metrics middleware               app_id=Napeequinox-Sword instance=jetson-nano scope=dapr.runtime.grpc.internal type=log ver=1.5.1
> INFO[0000] internal gRPC server is running on port 45707  app_id=Napeequinox-Sword instance=jetson-nano scope=dapr.runtime type=log ver=1.5.1
> INFO[0000] actor runtime started. actor idle timeout: 1h0m0s. actor scan interval: 30s  app_id=Napeequinox-Sword instance=jetson-nano scope=dapr.runtime.actor type=log ver=1.5.1
> WARN[0000] app channel not initialized, make sure -app-port is specified if pubsub subscription is required  app_id=Napeequinox-Sword instance=jetson-nano scope=dapr.runtime type=log ver=1.5.1
> WARN[0000] failed to read from bindings: app channel not initialized   app_id=Napeequinox-Sword instance=jetson-nano scope=dapr.runtime type=log ver=1.5.1
> INFO[0000] dapr initialized. Status: Running. Init Elapsed 9.225825ms  app_id=Napeequinox-Sword instance=jetson-nano scope=dapr.runtime type=log ver=1.5.1
> INFO[0000] placement tables updated, version: 0          app_id=Napeequinox-Sword instance=jetson-nano scope=dapr.runtime.actor.internal.placement type=log ver=1.5.1
> ℹ️  Checking if Dapr sidecar is listening on GRPC port 34427
> ℹ️  Dapr sidecar is up and running.
> ✅  You're up and running! Dapr logs will appear here.

I added... 

`--log-level debug`

...and see the following output from the test DAPR sidecar which I don't understand. From all of my reading, the "app channel is not initialized" error occurs when no `--app-port` is provided. In this case, the DAPR test sidecar only needs to listen on port HTTP 3500 for requests so there _is_ no `--app-port`. 

> DEBU[0058] retry count: 1, grpc call failed, ns: , addr: 192.168.50.150:37585, appid: greetinggrpc, err: rpc error: code = Internal desc = app channel is not initialized  app_id=Slavelaser-Raven instance=jetson-nano scope=dapr.runtime.direct_messaging type=log ver=1.5.1

Any idea why this isn't working? I understand how this is supposed to work, but I don't understand why the app channel isn't getting initialized? Was there a breaking change to the DAPR CLI since the book was published that would cause the instructions from the book to no longer work? Can anyone confirm if they are seeing the same behavior?

**Comment by RadoslavGatev** [comment]
Hi @bcraun, 
Thanks for the thorough description of the issue!
I've just tested it on my machine (Windows) and it works. 

Unfortunately, I don't have a Jetson Nano to try it. I can probably test it on Ubuntu which should be close enough to the Jetson Linux although it won't be on ARM...

Let me know if you find something meanwhile.

**Comment by bcraun** [comment]
Hi @RadoslavGatev ,

Apologies for delay in responding as I've been on vacation and just now getting back to this.

Are you testing the app via WSL2 or on native Windows?

**Comment by bcraun** [comment]
Hi @RadoslavGatev , thanks for confirming. I'm not sure what was going on in my Jetson Linux environment, but after starting over from scratch and using `<PackageReference Include="Grpc.AspNetCore" Version="2.40.0" />` I was able to get it working on ARM64. You can close this issue.

**Comment by RadoslavGatev** [comment]
Thanks @bcraun!
